### PR TITLE
[Bug] Workspaces from non writeable configurations cannot be updated

### LINKED ISSUE #470: [Bug] Workspaces from non writeable configurations cannot be updated
### Improvement description

since configurations cannot be saved, also workspace settings are not updated in table.

### PR DESCRIPTION
**Pull request by mcop1**
resolves #470

### CODE REVIEW

File: src/Command/Configuration/RebuildWorkspacesCommand.php [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+     *
+     * @throws \Exception
+     */
+    public function execute(InputInterface $input, OutputInterface $output)
+    {
+        $list = [];
+        $options = $input->getOption('configs');
+        if ($options) {
+            $option = $input->getOption('configs');
+            $configs = explode(',', $option);
```
Comment (kingjia90) [inline src/Command/Configuration/RebuildWorkspacesCommand.php]: everything seems working fine, but this $option and $options with same values, is there any reason for this?

probably it was meant to be like this:

```suggestion
        $options = $input->getOption('configs');
        if ($options) {
            $configs = explode(',', $options);
```

**Review by kingjia90 — CHANGES_REQUESTED** [review]
