### PR TITLE
[Bug]: Fetching asset in format WebP doesn't work

### LINKED ISSUE #541: [Bug]: Fetching asset in format WebP doesn't work
### Expected behavior

Hey,

following the documentation of Pimcore Data Hub as followed ...
https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Request

... I'm **expecting Data Hub to return assets in format WebP**, see: https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Response

Screenshot from 2022-06-03 11-36-29

### Actual behavior

Instead the Data Hub Endpoint **returns assets in format JPEG only** ...

Screenshot from 2022-06-03 11-37-07

### Steps to reproduce

Use documented request as followed ...
https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Request

... and send it via GraphQL Playground to this endpoint:
https://demo.pimcore.com/pimcore-datahub-webservices/explorer/products?apikey=6332aa5e6d3d6c0be31da2a8b3442113 

Any ideas or hints welcome.

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #541 

format argument should be working for srcset, resolutions, data and fullpath. 
Please test with a pimcore/pimcore version lower than 10.5 too

### CODE REVIEW

File: src/GraphQL/FieldHelper/AssetFieldHelper.php [hunk 1]
```diff
@@ -23,6 +23,47 @@
...
+        }
+
+        return null;
+    }
+
+    public function getImageDocumentThumbnail(Asset $asset, string | Image\Thumbnail\Config $thumbNailConfig, string $thumbNailFormat = null): mixed
+    {
+        if ($asset instanceof Asset\Document || $asset instanceof Asset\Video) {
+            $thumb = $asset->getImageThumbnail($thumbNailConfig);
+        } else {
```
Comment (blankse) [inline src/GraphQL/FieldHelper/AssetFieldHelper.php:48]: This should fix the new PhpStan error, right?
```suggestion
        } elseif ($asset instanceof Asset\Image) {
```

Comment (mcop1) [reply src/GraphQL/FieldHelper/AssetFieldHelper.php:48]: Yes, this sould fix the error, but then $thumb would be undefined. I´ll add a check with the next commit, thanks!

File: doc/10_GraphQL/04_Query/11_Query_Samples/11_Sample_GetAsset.md [hunk 2]
```diff
@@ -8,6 +8,7 @@ Deeplink: [http://pimcore-demo-basic.pim.zone/admin/login/deeplink?asset_4_image
 ### Request
 
 Note that for the fullpath and the base64 encoded data you can specify a thumbnail config.
+You can you the `format` argument to retrieve the values for a specific format like `webp`.
```
Comment (dvesh3) [inline doc/10_GraphQL/04_Query/11_Query_Samples/11_Sample_GetAsset.md]:
```suggestion
You can use the `format` argument to retrieve the values for a specific format like `webp`.
```

File: doc/10_GraphQL/04_Query/11_Query_Samples/11_Sample_GetAsset.md [hunk 3]
```diff
@@ -54,15 +55,15 @@ Note that for the fullpath and the base64 encoded data you can specify a thumbna
             "getAsset": {
               "id": "4",
               "fullpath": "/Car%20Images/jaguar/auto-automobile-automotive-192499.jpg",
-              "assetThumb": "/Car%20Images/jaguar/image-thumb__4__exampleCover/auto-automobile-automotive-192499.webp",
-              "assetThumb2": "/Car%20Images/jaguar/image-thumb__4__content/auto-automobile-automotive-192499.webp",
+              "assetThumb": "/Car%20Images/jaguar/4/image-thumb__4__exampleCover/auto-automobile-automotive-192499.jpg",
```
Comment (dvesh3) [inline doc/10_GraphQL/04_Query/11_Query_Samples/11_Sample_GetAsset.md:58]: Is this a BC break as now it returns a different format when no format argument is provided?

Comment (mcop1) [reply doc/10_GraphQL/04_Query/11_Query_Samples/11_Sample_GetAsset.md:58]: I think it is fine, because it changed in pimcore itself (in 2021 already), like Bernie mentioned here (https://github.com/pimcore/pimcore/discussions/10430#discussioncomment-1396465) . And the data-hub´s behaviour didn´t change with the pr, I just adapted the documentation.
