### PR TITLE
Fix: Labels get lowercased

### LINKED ISSUE #846: [Bug]: labels get lowercased
### Expected behavior

The labeled field is exported exactly like the label.

### Actual behavior

The labeled field is lowercased.

### Steps to reproduce

1. Create a field like so

```yaml
                                -
                                    isOperator: true
                                    attributes:
                                        label: Image
                                        type: operator
                                        class: assets
                                        children:
                                            -
                                                isOperator: false
                                                attributes:
                                                    label: 'Category Image'
                                                    type: value
                                                    class: DefaultValue
                                                    attribute: image
                                                    dataType: image
                                                    children: {  }
```

2. create a query like so

```graphql
getProductCategoryListing {edges {node {id, Image{id, fullpath, url}}}}
```

3. get error
```
GraphQL query failed: Cannot query field "Image" on type "object_ProductCategory". Did you mean "image" or "tags"?
```
4. try with lowercase label

```graphql
getProductCategoryListing {edges {node {id, image{id, fullpath, url}}}}
```

5. it works like that

### PR DESCRIPTION
**Pull request by blankse**
Fix: https://github.com/pimcore/data-hub/issues/846

### CODE REVIEW

File: src/GraphQL/DataObjectQueryOperatorConfigGenerator/Base.php [hunk 1]
```diff
@@ -59,10 +59,7 @@ public function getGraphQlType($typeName, $nodeDef, $class = null, $container =
     public function getGraphQlQueryOperatorConfig($typeName, $nodeDef, $class = null, $container = null, $params = [])
     {
         $attributes = $nodeDef['attributes'];
-        $label = (isset($attributes['label']) ? $attributes['label'] : '#' . uniqid());
-        $label = lcfirst($label);
-        $fieldname = preg_replace('/[^A-Za-z0-9\-\.~_]+/', '_', $label);
-
+        $fieldname = $this->getFieldname($attributes);
```
Comment (dkarlovi) [inline src/GraphQL/DataObjectQueryOperatorConfigGenerator/Base.php:62]: Tested, works.

**Review by dkarlovi — APPROVED** [review]

**Review by Corepex — APPROVED** [review]
@blankse thanks for fixing that issue :100:
