### PR TITLE
Fix Assets fullpath(thumbnail:) and data(thumbnail:) 

### LINKED ISSUE #121: Assets fullpath(thumbnail:) not working on relations
I'm trying to get thumbnail from asset linked by relation to an object, but I cannot get it to work. I tried to check over the code but without results.

To reproduce, this is a simple class:
image

This is an object created with that class:
image

This is the schema in datahub config:
image

This is a sample GraphQl Query tho show the error:
image

The field "thumb" in the asset linked by the relation is always the original asset path, never the thumbnail path. (As you can see in the direct getAsset query).

### PR DESCRIPTION
**Pull request by SimoneCarnio**
Should fix #121

### CODE REVIEW

File: src/GraphQL/AssetType/AssetType.php [hunk 1]
```diff
@@ -104,7 +112,39 @@ public function build(&$config)
...
+                                $thumb = $image->getImageThumbnail($args['thumbnail']);
+                                return base64_encode(file_get_contents($thumb->getFileSystemPath()));
+                            } else {
+                                return base64_encode(file_get_contents($image->getFileSystemPath()));
+                            }
+                        }
+                    }
+                    return null;
+                }
+            ],
```
Comment (weisswurstkanone) [inline src/GraphQL/AssetType/AssetType.php]: I think there is something wrong with the brackets here. Could you please double-check ?

**Comment by weisswurstkanone** [comment]
thx!
